FROM ubuntu:22.04
LABEL author=Roman
WORKDIR /var/www/html
RUN apt-get update
RUN apt-get install apache2 -y
COPY /files/index.html .
COPY /files/script.sh /opt/script.sh
RUN chmod +x /opt/script.sh
ENV OWNER=Roman
ENV TYPE=Demo
EXPOSE 80
CMD ["/opt/script.sh"]


