apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: observability
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: grafana.local.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kps-grafana  # из твоего get svc
                port:
                   number: 80