INSERT INTO products (name, description, image, price) VALUES
('Apple iPhone 14', 'Latest iPhone model with A15 Bionic chip.', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQAKPwwOHE6Q9Dgn2NY9DGpOk0-CoEobgUv75jIr8Pfe3kX_eGpeUb1O9Ujb6zYvpiSVCHm5-Pmgpba4nEqNSp8Ucelu6VG-t0gx35AqOrPVGR2U9qaasKlwFOXGQCUcW1WrWNro1M8pu4&usqp=CAc', 799.00),
('Samsung Galaxy S23', 'Premium Android phone with stunning display.', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRDGtvHBscuFhYiT-1q442yk1sQX8gHQnZX7IcOLB2-BZy2TxY5ncSupPzZVDq5GEz1MIsuUPJTrUluPn633-q147wFr2GE3J6icr1G0yV3wNoNsrlbFSuh40NCFfTyqi9OLO9VceEq9g&usqp=CAc', 799.99),
('Sony WH-1000XM5', 'Noise-cancelling headphones with great sound quality.', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQC8nFoSRtg5Kn5LOiWa920Iu-4BsSCcNsoVEb5UlgI_oeaAjhU-QzLyej3xNjpIUcaqGlSqYF5xBC7rYehtvxn3c1cXrMzPlACZtFIFsCuBSbHxqc_lKGWFtr0FlmkrjWULw1uoEA&usqp=CAc', 399.99),
('Dell XPS 13', 'Ultrabook with amazing performance and design.', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTGAApiJsH-EuCkCqCHiZ5KNSj9sek4bCoGnvZaML8B__3AosJU5_eAj5HXVhF05ZG2Xosk9r-HATPuXRYCoe9WzT0DCPi_jY_Bw-nv3pPaCgc-Imk7CP1yFZUpcB9XOjWfm3ShygacPUc&usqp=CAc', 999.99),
('Apple MacBook Air M2', 'Lightweight laptop with Apple Silicon chip.', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRvjkP_FwqMkZXKXefwoaspJbaMVJ0B1_WGQhOW0TkYy8EyFD5opTVAwFoOPhPunrvAjg5KvQSNlbcJ7Q13wbE83NnVOuecyISvgicPnn6nX8GGb1ufo09PXIAqTGRVFXLAug60JHvUhA&usqp=CAc', 1199.00),
('PlayStation 5', 'Next-gen console with fast loading and 4K gaming.', 'https://via.placeholder.com/150', 499.99),
('Xbox Series X', 'Powerful console with Game Pass subscription.', 'https://via.placeholder.com/150', 499.99),
('Nintendo Switch OLED', 'Portable gaming console with OLED display.', 'https://via.placeholder.com/150', 349.99),
('Bose QuietComfort Earbuds II', 'Wireless earbuds with active noise cancellation.', 'https://via.placeholder.com/150', 299.00),
('GoPro HERO11 Black', 'Action camera for adventures and vlogging.', 'https://via.placeholder.com/150', 499.99),
('Canon EOS R5', 'Professional mirrorless camera with 45MP sensor.', 'https://via.placeholder.com/150', 3899.00),
('DJI Mini 3 Pro', 'Compact drone with 4K video and intelligent flight modes.', 'https://via.placeholder.com/150', 759.00),
('Samsung QLED TV 55"', 'Stunning 4K QLED TV with vibrant colors.', 'https://via.placeholder.com/150', 699.99),
('LG OLED C2 65"', 'High-end OLED TV with amazing contrast and clarity.', 'https://via.placeholder.com/150', 1999.99),
('Apple Watch Series 8', 'Smartwatch with health tracking and crash detection.', 'https://via.placeholder.com/150', 399.00),
('Garmin Fenix 7', 'Premium multisport GPS watch for adventurers.', 'https://via.placeholder.com/150', 699.99),
('Dyson V15 Detect', 'Cordless vacuum cleaner with laser dust detection.', 'https://via.placeholder.com/150', 699.99),
('Instant Pot Duo 7-in-1', 'Multifunctional cooker for easy meals.', 'https://via.placeholder.com/150', 89.99),
('KitchenAid Stand Mixer', 'Classic mixer for baking enthusiasts.', 'https://via.placeholder.com/150', 379.99),
('Anova Precision Cooker', 'Sous vide cooker for perfect temperature control.', 'https://via.placeholder.com/150', 199.00),
('Sony PlayStation VR2', 'VR headset for an immersive gaming experience.', 'https://via.placeholder.com/150', 549.99),
('Meta Quest 2', 'Standalone VR headset with a library of games.', 'https://via.placeholder.com/150', 299.99),
('Lenovo ThinkPad X1 Carbon', 'Business laptop with durability and performance.', 'https://via.placeholder.com/150', 1299.00),
('Microsoft Surface Pro 9', 'Versatile 2-in-1 laptop with pen support.', 'https://via.placeholder.com/150', 999.99),
('JBL Charge 5', 'Portable waterproof Bluetooth speaker.', 'https://via.placeholder.com/150', 179.95),
('Sonos Beam (Gen 2)', 'Smart soundbar with Dolby Atmos support.', 'https://via.placeholder.com/150', 449.00),
('Razer BlackWidow V3', 'Mechanical gaming keyboard with RGB lighting.', 'https://via.placeholder.com/150', 139.99),
('Logitech MX Master 3S', 'Ergonomic wireless mouse for professionals.', 'https://via.placeholder.com/150', 99.99),
('HyperX Cloud Alpha', 'Gaming headset with great sound and comfort.', 'https://via.placeholder.com/150', 99.99),
('Asus ROG Zephyrus G14', 'Gaming laptop with powerful specs in a compact design.', 'https://via.placeholder.com/150', 1499.99),
('Alienware Aurora R13', 'High-performance gaming desktop.', 'https://via.placeholder.com/150', 1999.99),
('HP Envy 6055e', 'All-in-one wireless printer for home use.', 'https://via.placeholder.com/150', 129.99),
('Fitbit Charge 5', 'Fitness tracker with advanced health features.', 'https://via.placeholder.com/150', 179.95),
('Samsung Galaxy Tab S8', 'High-end Android tablet with S Pen.', 'https://via.placeholder.com/150', 899.99),
('Apple iPad Pro 12.9"', 'Powerful tablet with M2 chip.', 'https://via.placeholder.com/150', 1099.00),
('Google Pixel 7 Pro', 'Flagship phone with exceptional camera.', 'https://via.placeholder.com/150', 899.00),
('Amazon Echo Dot (5th Gen)', 'Compact smart speaker with Alexa.', 'https://via.placeholder.com/150', 49.99),
('Ring Video Doorbell 4', 'Smart doorbell with 1080p video and alerts.', 'https://via.placeholder.com/150', 199.99),
('Philips Hue Starter Kit', 'Smart lighting system with app control.', 'https://via.placeholder.com/150', 189.99),
('Nespresso Vertuo Next', 'Coffee maker for barista-quality espresso.', 'https://via.placeholder.com/150', 159.00),
('Breville Barista Express', 'Semi-automatic espresso machine for coffee lovers.', 'https://via.placeholder.com/150', 699.95),
('Roku Streaming Stick 4K', 'Streaming device with HDR and Dolby Vision.', 'https://via.placeholder.com/150', 49.99),
('Fire TV Cube (3rd Gen)', 'Smart streaming device with Alexa.', 'https://via.placeholder.com/150', 119.99),
('Xiaomi Mi Band 7', 'Affordable fitness tracker with long battery life.', 'https://via.placeholder.com/150', 49.99),
('Apple AirTag', 'Compact tracker for finding your belongings.', 'https://via.placeholder.com/150', 29.00),
('Samsung T7 Portable SSD', 'Fast and compact external storage.', 'https://via.placeholder.com/150', 89.99),
('WD My Cloud Home', 'Network-attached storage for easy backups.', 'https://via.placeholder.com/150', 159.99),
('Seagate IronWolf 8TB', 'Hard drive for NAS with high reliability.', 'https://via.placeholder.com/150', 229.99),
('Crucial P5 Plus 1TB', 'NVMe SSD for blazing-fast performance.', 'https://via.placeholder.com/150', 179.99),
('LG Gram 17', 'Ultra-light laptop with a large screen.', 'https://via.placeholder.com/150', 1799.99),
('Samsung Galaxy Buds2 Pro', 'High-quality wireless earbuds with ANC.', 'https://via.placeholder.com/150', 229.99),
('Razer Kraken V3', 'Gaming headset with THX Spatial Audio.', 'https://via.placeholder.com/150', 99.99),
('Corsair K70 RGB MK.2', 'Premium mechanical gaming keyboard.', 'https://via.placeholder.com/150', 159.99),
('Cooler Master MM711', 'Lightweight gaming mouse with RGB.', 'https://via.placeholder.com/150', 49.99),
('MSI GeForce RTX 4090', 'High-end graphics card for gaming and AI.', 'https://via.placeholder.com/150', 1499.99),
('AMD Ryzen 9 7950X', 'Top-of-the-line processor for gaming and productivity.', 'https://via.placeholder.com/150', 699.00),
('Intel Core i9-13900K', 'Flagship CPU with powerful multi-threading.', 'https://via.placeholder.com/150', 589.99),
('EVGA 850W PSU', 'Reliable power supply with 80+ Gold certification.', 'https://via.placeholder.com/150', 129.99),
('Thermaltake Tower 900', 'Premium PC case for custom builds.', 'https://via.placeholder.com/150', 249.99),
('Sony Alpha A7 IV', 'Mirrorless camera with advanced features.', 'https://via.placeholder.com/150', 2499.99),
('Fujifilm X-T4', 'Stylish camera for photographers and vloggers.', 'https://via.placeholder.com/150', 1699.99),
('Panasonic Lumix GH6', 'Mirrorless camera for videographers.', 'https://via.placeholder.com/150', 2199.99),
('Sigma 24-70mm f/2.8', 'Versatile lens for photography and video.', 'https://via.placeholder.com/150', 1099.00),
('Tamron 70-180mm f/2.8', 'Compact telephoto lens for portraits and sports.', 'https://via.placeholder.com/150', 1199.00),
('BenQ PD3220U', '4K monitor with HDR for professionals.', 'https://via.placeholder.com/150', 1199.99),
('ASUS ProArt PA32UCX', 'High-end monitor with wide color gamut.', 'https://via.placeholder.com/150', 2999.99),
('Dell UltraSharp U2723QE', '27-inch 4K monitor with incredible accuracy.', 'https://via.placeholder.com/150', 779.99),
('Epson EcoTank ET-3850', 'Printer with refillable ink tanks for low-cost printing.', 'https://via.placeholder.com/150', 399.99),
('SteelSeries Arctis 9X', 'Wireless gaming headset with Xbox compatibility.', 'https://via.placeholder.com/150', 199.99),
('HyperX Alloy Origins', 'Compact mechanical keyboard with RGB.', 'https://via.placeholder.com/150', 109.99),
('Gigabyte Aorus 17', 'High-performance gaming laptop.', 'https://via.placeholder.com/150', 2499.99),
('Asus TUF Dash F15', 'Affordable gaming laptop with great performance.', 'https://via.placeholder.com/150', 1099.99),
('Lenovo Legion 5 Pro', 'Gaming laptop with excellent cooling and display.', 'https://via.placeholder.com/150', 1399.99),
('Razer Blade 15', 'Sleek and powerful gaming laptop.', 'https://via.placeholder.com/150', 1999.99),
('Alienware m15 R6', 'Portable gaming laptop with powerful specs.', 'https://via.placeholder.com/150', 1799.99),
('NZXT H510 Elite', 'Compact PC case with tempered glass panels.', 'https://via.placeholder.com/150', 149.99),
('Corsair iCUE 5000X', 'Mid-tower case with RGB and airflow.', 'https://via.placeholder.com/150', 204.99),
('Logitech StreamCam', 'Webcam optimized for live streaming.', 'https://via.placeholder.com/150', 169.99),
('Elgato Stream Deck', 'Customizable control panel for streamers.', 'https://via.placeholder.com/150', 249.99),
('Blue Yeti X', 'High-quality USB microphone for podcasting and streaming.', 'https://via.placeholder.com/150', 169.99),
('Rode NT1-A', 'Studio condenser microphone for recording.', 'https://via.placeholder.com/150', 229.00),
('Zoom H6', 'Portable recorder for audio professionals.', 'https://via.placeholder.com/150', 349.99),
('Shure SM7B', 'Legendary vocal microphone for studio recording.', 'https://via.placeholder.com/150', 399.00),
('Focusrite Scarlett 2i2', 'Popular audio interface for home studios.', 'https://via.placeholder.com/150', 159.99),
('Apogee Duet 3', 'Premium audio interface for professionals.', 'https://via.placeholder.com/150', 649.00),
('Korg Minilogue XD', 'Versatile synthesizer for music production.', 'https://via.placeholder.com/150', 749.99),
('Akai MPC One', 'Standalone music production station.', 'https://via.placeholder.com/150', 899.00),
('Ableton Push 2', 'Controller for music production with Ableton Live.', 'https://via.placeholder.com/150', 799.00),
('Novation Launchpad Pro', 'MIDI controller for performance and production.', 'https://via.placeholder.com/150', 349.99),
('Arturia KeyLab 49 MkII', 'Professional MIDI keyboard controller.', 'https://via.placeholder.com/150', 449.00),
('Yamaha HS8', 'Studio monitor with accurate sound reproduction.', 'https://via.placeholder.com/150', 369.99),
('KRK Rokit 5 G4', 'Compact studio monitor for small studios.', 'https://via.placeholder.com/150', 179.00),
('PreSonus Eris E5', 'Affordable studio monitor with balanced sound.', 'https://via.placeholder.com/150', 99.99),
('Alesis Nitro Mesh Kit', 'Electronic drum kit for beginners.', 'https://via.placeholder.com/150', 379.00),
('Roland TD-17KVX', 'High-end electronic drum kit for drummers.', 'https://via.placeholder.com/150', 1999.99),
('Yamaha P-125', 'Digital piano with authentic sound.', 'https://via.placeholder.com/150', 649.99),
('Casio PX-S1100', 'Slim and portable digital piano.', 'https://via.placeholder.com/150', 699.99),
('Nord Stage 3', 'Professional keyboard for live performances.', 'https://via.placeholder.com/150', 4499.00),
('Kawai ES920', 'Portable digital piano with excellent sound.', 'https://via.placeholder.com/150', 1599.00),
('Behringer X32 Compact', 'Digital mixing console for live sound.', 'https://via.placeholder.com/150', 2599.99),
('Allen & Heath SQ-5', 'Compact digital mixer with advanced features.', 'https://via.placeholder.com/150', 2999.00),
('Pioneer DJ DDJ-1000', 'Professional DJ controller with Rekordbox.', 'https://via.placeholder.com/150', 1199.00),
('Denon DJ Prime 4', 'Standalone DJ system with 10-inch touchscreen.', 'https://via.placeholder.com/150', 1899.00),
('Numark Mixtrack Platinum FX', 'Affordable DJ controller with FX controls.', 'https://via.placeholder.com/150', 249.00);
