grafana:
  replicas: 1
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 2d
    storageSpec: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1500Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi