deploymentMode: SingleBinary

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:          
    path_prefix: /tmp   
  storage:
    type: filesystem
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraArgs:             
    "-config.file=/etc/loki/single-binary.yaml"
  securityContext:
    runAsUser: 10001
    fsGroup: 20001
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

gateway:
  enabled: false
lokiCanary:
  enabled: true
chunksCache:
  enabled: false
resultsCache:
  enabled: false

simpleScalable:
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
